const A = {
	REQ_LISTING: 'REQ_LISTING',
	REC_LISTING: 'REC_LISTING',
	REC_LISTING_ERR: 'REC_LISTING_ERR',
	REC_LISTING_CLEAR: 'REC_LISTING_CLEAR',
	REQ_SEARCH_LISTING: 'REQ_SEARCH_LISTING',
	REC_SEARCH_LISTING: 'REC_SEARCH_LISTING',
	REC_SEARCH_LISTING_ERR: 'REC_SEARCH_LISTING_ERR',
	REC_SEARCH_LISTING_CLEAR: 'REC_SEARCH_LISTING_CLEAR',
	REQ_SINGLE_LISTING: 'REQ_SINGLE_LISTING',
	REC_SINGLE_LISTING: 'REC_SINGLE_LISTING',
	REC_SINGLE_LISTING_ERR: 'REC_SINGLE_LISTING_ERR',
	REC_SINGLE_LISTING_CLEAR: 'REC_SINGLE_LISTING_CLEAR'
}

export default A
